update: job now successfully completes before keycloak deployment is made

diff --git a/keycloak-chart/templates/create-config-map.yaml b/keycloak-chart/templates/create-config-map.yaml
--- a/keycloak-chart/templates/create-config-map.yaml
+++ b/keycloak-chart/templates/create-config-map.yaml
@@ -2,10 +2,7 @@ apiVersion: batch/v1
 kind: Job
 metadata:
   name: {{ .Values.metadata.name }}
-  namespace: {{ .Values.metadata.namespace }}
-  annotations:
-    argocd.argoproj.io/hook: {{ .Values.metadata.annotations.hook }}
-    argocd.argoproj.io/hook-delete-policy: {{ .Values.metadata.annotations.hookDeletePolicy }}
+  namespace: {{ .Release.Namespace }}
 spec:
   template:
     spec:
@@ -17,6 +14,24 @@ spec:
           - "-c"
           - |
             aws s3 cp s3://{{ .Values.awsCli.s3Bucket }}/.env {{ .Values.awsCli.envFilePath }}
+        env:
+          - name: AWS_ACCESS_KEY_ID
+            valueFrom:
+              secretKeyRef:
+                name: {{ .Values.awsCli.secretName }}
+                key: {{ .Values.awsCli.accessKeyID }}
+          - name: AWS_SECRET_ACCESS_KEY
+            valueFrom:
+              secretKeyRef:
+                name: {{ .Values.awsCli.secretName }}
+                key: {{ .Values.awsCli.secretAccessKey }}
+          - name: AWS_SESSION_TOKEN
+            valueFrom:
+              secretKeyRef:
+                name: {{ .Values.awsCli.secretName }}
+                key: {{ .Values.awsCli.sessionToken }}
+          - name: AWS_DEFAULT_REGION
+            value: {{ .Values.awsCli.region }}
         volumeMounts:
           - name: {{ .Values.volumeMounts.name }}
             mountPath: {{ .Values.volumeMounts.mountPath }}
@@ -28,7 +43,14 @@ spec:
           - "-c"
           - |
             sleep {{ .Values.kubectl.sleepDuration }}
-            kubectl create configmap keycloak-env-config --from-file=/tmp/.env --namespace=datev-wallet --dry-run=client -o yaml | kubectl apply -f -
+            echo "Creating configmap..."
+            kubectl create configmap keycloak-env-config --from-file={{ .Values.awsCli.envFilePath }} --namespace={{ .Values.metadata.namespace }} --dry-run=client -o yaml | kubectl apply -f -
+            if [ $? -eq 0 ]; then
+              echo "Configmap created successfully"
+            else
+              echo "Failed to create configmap"
+              exit 1
+            fi
         volumeMounts:
           - name: {{ .Values.volumeMounts.name }}
             mountPath: {{ .Values.volumeMounts.mountPath }}
